version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto11

  pre_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - mvn clean
    - mvn validate
    - echo Build ends on 'date'

  build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - mvn compile
    - mvn test
    - echo Build ends on 'date'

  post_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - mvn package
    - mv ./target/**.war helloworld.war
    - echo Build edns on 'date'

artifacts:
  fils:
    - helloworld.war
  name: hello-word-artifact


